language: android
jdk: oraclejdk7
android:
  components:
    # The BuildTools version used
    - build-tools-21.1.1

    # The SDK version used
    - android-21

    # System image used
    - sys-img-armeabi-v7a-android-19

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
